version: "3.8"

services:
  database:
    container_name: postgresql_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - database

  migration:
    image: zernat/captcha_solving_api-development:latest
    command: bash -c "alembic revision --autogenerate -m 'New Migration'"
    depends_on:
      - pgadmin

  upgrade_head:
    image: zernat/captcha_solving_api-development:latest
    command: bash -c "alembic upgrade head"
    depends_on:
      - migration

  captcha_solving_api:
    container_name: captcha_solving_api
    image: zernat/captcha_solving_api-development:latest
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "80:8000"
    depends_on:
      - upgrade_head
    environment:
      WAIT_HOSTS: postgres:5432
    restart: always
